---

spring:
  profiles: cloud

info:
  description: Company configuration repo
  message: cloud profile details

---

spring:
  profiles: test

info:
  description: Company configuration repo
  message: test profile details